baseURL = "/"
languageCode = "en-us"
title = "Hello, there!"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Roman Golev"
    description = "My name is Roman Golev and it's my webpage ðŸš§ At maintenence now ðŸš§"
    githubUsername = "#"
    accent = " #0070b9 "
    showBorder = true
    backgroundColor = "#E8E8E8"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:rv.golev@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/romangolev"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/roman_golev"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/romangolev/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.facebook.com/rv.golev"
    name = "fab fa-facebook"
    weight = 5

[[menu.icon]]
    url = "https://www.instagram.com/rv.golev/"
    name = "fab fa-instagram"
    weight = 6

[[menu.icon]]
    url = "https://www.youtube.com/@romangolev"
    name = "fab fa-youtube"
    weight = 7